name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.48.156.60
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            if [ -d "healthapp-frontend" ]; then
              cd healthapp-frontend && git pull origin main
            else
              git clone https://github.com/aneeq885/healthapp-frontend.git
              cd healthapp-frontend
            fi
            docker stop healthapp-frontend || true
            docker rm healthapp-frontend || true
            docker build -t healthapp-frontend .
            docker run -d \
              --name healthapp-frontend \
              --network healthapp-net \
              -p 3001:3000 \
              --restart always \
              healthapp-frontend